---
title: "04 Model Combination: Insight Edge"
output: html_document
date: "2025-08-01"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Working Directory
```{r}
setwd("C:/Users/Valerie/OneDrive - Singapore University of Technology and Design/00 YJ personal/00 Academics/00 Term 5 Mods/40.016 The Analytics Edge/00 1D Project/Submissions")
rm(list=ls())
```

# Load outputs from other models
```{r}
# Load probabilities
xgb_preds <- read.csv("XGBoost_Model_Insight_Edge_Probabilities.csv")  # assumes columns: id, ch1, ch2, ch3, ch4
cat_preds <- read.csv("CatBoost_Model_Insight_Edge_Probabilities.csv")  # assumes same column structure
m_logit <- read.csv("Multilogit_Model_Insight_Edge_Probabilities.csv")

# Check structure
head(xgb_preds)
head(cat_preds)
head(m_logit)
```


# Average Probabilities
```{r}
# Weighted sum of predictions
ensemble_raw <- 0.70 * cat_preds + 0.20 * xgb_preds + 0.10 * m_logit

# Normalize (only Ch1 to Ch4 columns)
ch_cols <- c("Ch1", "Ch2", "Ch3", "Ch4")
ensemble_raw[ch_cols] <- ensemble_raw[ch_cols] / rowSums(ensemble_raw[ch_cols])

# Final output
ensemble_preds <- ensemble_raw

```


# Export Ensemble Predictions
```{r}
write.csv(ensemble_preds, "Final_Insight_Edge_Probabilities.csv", row.names = FALSE)
```